#!/bin/bash
jslint \
  --indent 2 \
  --browser \
  --predef jasmine \
  --predef describe \
  --predef it \
  --predef beforeEach \
  --predef expect \
  --predef jQuery \
  src/*.js spec/**/*.js spec/*.js
